import { Rental } from './rental.types';
import { BillStatus } from './types';

// ============= BILL TYPES =============

export type BillItemType = 'rent' | 'utility' | 'service' | 'other';
export type CostType = 'fixed' | 'per_person' | 'metered';

export interface MeterReadingInfo {
	lastReading: number;
	currentReading: number;
	consumption: number;
	unit: string;
}

export interface BillItem {
	id: string;
	billId: string;
	itemType: BillItemType;
	itemName: string;
	description?: string;
	quantity?: number;
	unitPrice?: number;
	amount: number;
	currency: string;
	notes?: string;
	roomCostId?: string;
	costType?: CostType;
	meterReading?: MeterReadingInfo;
	prorationFactor?: number;
	createdAt: Date | string;
	updatedAt?: Date | string;
}

export interface MeteredCostToInput {
	roomCostId: string;
	name: string;
	unit: string;
	unitPrice: number;
	currency: string;
	currentReading: number;
	lastReading: number;
	lastMonthReading: number;
	requiresInput: boolean;
	notes?: string;
}

export interface Bill {
	id: string;
	rentalId: string;
	roomInstanceId: string;
	billingPeriod: string; // "2025-01" (YYYY-MM)
	billingMonth: number; // 1-12
	billingYear: number; // 2025
	periodStart: Date | string; // "2025-01-01"
	periodEnd: Date | string; // "2025-01-31"
	rentalStartDate?: Date | string;
	rentalEndDate?: Date | string;
	occupancyCount?: number;
	subtotal: number;
	discountAmount: number;
	taxAmount: number;
	totalAmount: number;
	paidAmount: number;
	remainingAmount: number;
	status: BillStatus;
	dueDate: Date | string;
	paidDate?: Date | string;
	notes?: string;
	isAutoGenerated?: boolean;
	requiresMeterData?: boolean;
	createdAt: Date | string;
	updatedAt: Date | string;
	// Relations
	billItems?: BillItem[];
	rental?: Rental;
	meteredCostsToInput?: MeteredCostToInput[];
}

export interface MeterReading {
	roomCostId: string;
	currentReading: number;
	lastReading: number;
}

export interface CreateBillRequest {
	roomInstanceId: string;
	billingPeriod: string; // "2025-01" (YYYY-MM)
	billingMonth: number; // 1-12
	billingYear: number; // 2025
	periodStart: string; // "2025-01-01"
	periodEnd: string; // "2025-01-31"
	occupancyCount: number; // số người ở
	meterReadings: MeterReading[];
	notes?: string;
}

export interface PreviewBillForBuildingRequest {
	buildingId: string;
	billingPeriod?: string;
	billingMonth?: number;
	billingYear?: number;
	periodStart?: string;
	periodEnd?: string;
}

export interface GenerateMonthlyBillsRequest {
	buildingId: string;
	billingPeriod?: string;
	billingMonth?: number;
	billingYear?: number;
	periodStart?: string;
	periodEnd?: string;
}

export interface GenerateMonthlyBillsResponse {
	message: string;
	billsCreated: number;
	billsExisted: number;
}

export interface UpdateBillRequest {
	dueDate?: string;
	notes?: string;
	status?: BillStatus;
	discountAmount?: number;
	taxAmount?: number;
	totalAmount?: number;
}

export interface UpdateMeterDataRequest {
	meterData: MeterReading[];
}

export interface UpdateBillWithMeterDataRequest {
	billId: string;
	occupancyCount: number;
	meterData: MeterReading[];
}

export interface BillQueryParams {
	page?: number;
	limit?: number;
	status?: BillStatus;
	search?: string;
	billingMonth?: number;
	billingYear?: number;
	rentalId?: string;
	roomInstanceId?: string;
	fromDate?: string;
	toDate?: string;
	billingPeriod?: string;
}

export interface LandlordBillQueryParams {
	page?: number;
	limit?: number;
	buildingId?: string;
	roomInstanceId?: string;
	billingPeriod?: string;
	billingMonth?: number;
	billingYear?: number;
	status?: BillStatus;
	search?: string;
	sortBy?: 'roomName' | 'status' | 'totalAmount' | 'createdAt' | 'dueDate';
	sortOrder?: 'asc' | 'desc';
}

export interface PaginatedBillResponse {
	data: Bill[];
	meta: {
		page: number;
		limit: number;
		total: number;
		totalPages: number;
	};
}

export interface PayOSLinkRequest {
	returnUrl?: string;
	cancelUrl?: string;
}

export interface PayOSLinkResponse {
	checkoutUrl: string;
	qrCode?: string;
	orderCode: number;
	amount: number;
	currency: string;
	description: string;
	paymentLinkId: string;
	expiredAt: number;
}

// ============= CREATE BILL FOR ROOM INSTANCE =============
export interface CreateBillForRoomRequest {
	roomInstanceId: string;
	billingPeriod: string; // "2025-01" (YYYY-MM)
	billingMonth: number; // 1-12
	billingYear: number; // 2025
	periodStart: string; // "2025-01-01"
	periodEnd: string; // "2025-01-31"
	occupancyCount: number; // số người ở
	meterReadings: MeterReading[];
	notes?: string;
}
